name: Multi Event Workflow

on:
  push:
    branches:
      - main
      - production

  pull_request:
    branches:
      - main
      - production

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Run on push
        run: echo "Hello, world! on push"

  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Run on pull request
        run: echo "Hello, world! on pull request"
